# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: "bean0234/muno"
  NAME: "muno"
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }} 
          
      - name: Build and push
        uses: docker/build-push-action@v2 # build-push-action 사용
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
  deploy:
    needs: build
    name: DEPLOY 
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }} 
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.IMAGE_NAME }}:latest
          docker run -d -p 80:8080 --name ${{ env.NAME }} --restart always  -e DATABASEUR=${{ secrets.DB_URL }} ${{ env.IMAGE_NAME }}:latest
